# Generated by Django 3.0.7 on 2022-04-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ICDRBackup",
        ),
    ]
