# Generated by Django 4.1.5 on 2023-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BPDropinSupplyRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskID", models.CharField(max_length=50, null=True)),
                ("waveID", models.CharField(max_length=50, null=True)),
                ("taskType", models.CharField(max_length=50, null=True)),
                ("fromPart", models.CharField(max_length=50, null=True)),
                ("fromStorageZone", models.CharField(max_length=50, null=True)),
                ("toLocation", models.CharField(max_length=50, null=True)),
                ("createdDate", models.CharField(max_length=50, null=True)),
                ("createdTime", models.CharField(max_length=50, null=True)),
                ("timestamp", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "mNFG Supply Red Items",
                "verbose_name_plural": "mNFG Supply Red Items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BPDropinSupplyReportRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.CharField(blank="true", max_length=100, null=True)),
                ("timestamp", models.CharField(max_length=200, null=True)),
                ("turno", models.CharField(blank="true", max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BPSMDSupplyRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskID", models.CharField(max_length=50, null=True)),
                ("waveID", models.CharField(max_length=50, null=True)),
                ("taskType", models.CharField(max_length=50, null=True)),
                ("fromPart", models.CharField(max_length=50, null=True)),
                ("fromStorageZone", models.CharField(max_length=50, null=True)),
                ("toLocation", models.CharField(max_length=50, null=True)),
                ("createdDate", models.CharField(max_length=50, null=True)),
                ("createdTime", models.CharField(max_length=50, null=True)),
                ("timestamp", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "mNFG Supply Red Items",
                "verbose_name_plural": "mNFG Supply Red Items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BPSMDSupplyReportRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.CharField(blank="true", max_length=100, null=True)),
                ("timestamp", models.CharField(max_length=200, null=True)),
                ("turno", models.CharField(blank="true", max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FASupplyRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskID", models.CharField(max_length=50, null=True)),
                ("waveID", models.CharField(max_length=50, null=True)),
                ("taskType", models.CharField(max_length=50, null=True)),
                ("fromPart", models.CharField(max_length=50, null=True)),
                ("fromStorageZone", models.CharField(max_length=50, null=True)),
                ("toLocation", models.CharField(max_length=50, null=True)),
                ("createdDate", models.CharField(max_length=50, null=True)),
                ("createdTime", models.CharField(max_length=50, null=True)),
                ("timestamp", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "mNFG Supply Red Items",
                "verbose_name_plural": "mNFG Supply Red Items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FaSupplyReportRedItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.CharField(blank="true", max_length=100, null=True)),
                ("timestamp", models.CharField(max_length=200, null=True)),
                ("turno", models.CharField(blank="true", max_length=1, null=True)),
            ],
            options={
                "verbose_name": "FaSupplyReportRedItems",
                "verbose_name_plural": "FaSupplyReportRedItems",
                "managed": True,
            },
        ),
    ]
