# Generated by Django 4.1.5 on 2023-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receiving",
            "0002_bpdropinsupplyreditems_bpdropinsupplyreportreditems_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Receiving_SupplyPages_Refresh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastUpdate", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
