# Generated by Django 3.0.7 on 2022-04-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0002_delete_icdrbackup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICDRBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aberturaICDR",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                ("ageing", models.CharField(blank="true", max_length=150, null=True)),
                ("nAno", models.CharField(blank="true", max_length=150, null=True)),
                (
                    "fornecedor",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "partnumber",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "quantidade",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                ("tipo", models.CharField(blank="true", max_length=150, null=True)),
                ("simNao", models.CharField(blank="true", max_length=150, null=True)),
                (
                    "responsavel",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "departamento",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "comentarioFecho",
                    models.CharField(blank="true", max_length=2000, null=True),
                ),
                (
                    "rctUnpCheck",
                    models.CharField(blank="true", max_length=50, null=True),
                ),
                (
                    "cycleCountCheck",
                    models.CharField(blank="true", max_length=50, null=True),
                ),
                (
                    "consumption",
                    models.CharField(blank="true", max_length=500, null=True),
                ),
                ("po", models.CharField(blank="true", max_length=2000, null=True)),
                ("date", models.CharField(blank="true", max_length=150, null=True)),
                (
                    "comentarioFechoICDR",
                    models.CharField(blank="true", max_length=2000, null=True),
                ),
                (
                    "cycleCount",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "dataCycleCount",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                ("unCost", models.CharField(blank="true", max_length=150, null=True)),
                (
                    "totalCost",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "comentarioReporting",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
                (
                    "auditCheck",
                    models.CharField(blank="true", max_length=150, null=True),
                ),
            ],
            options={
                "verbose_name": "Receiving - ICDR - BACKUP",
                "verbose_name_plural": "Receiving - ICDR - BACKUP",
                "managed": True,
            },
        ),
    ]
