# Generated by Django 4.1.5 on 2023-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0003_receiving_supplypages_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiving_supplypages_refresh",
            name="estado",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
