# Generated by Django 4.1.5 on 2023-04-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0006_historicoerros_delete_receiving_supplypages_refresh"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoErros_View",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagina", models.CharField(max_length=100, null=True)),
                ("erro", models.CharField(max_length=200, null=True)),
                ("timestamp", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "receiving_historicoerros",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MNFGSupplyItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wtsk_id", models.CharField(max_length=50, null=True)),
                ("wtsk_event_id", models.CharField(max_length=50, null=True)),
                ("wtsk_wave_id", models.CharField(max_length=50, null=True)),
                ("wtsk_task_type", models.CharField(max_length=50, null=True)),
                ("wtsk_from_part", models.CharField(max_length=50, null=True)),
                ("wtsk_from_stor_zone", models.CharField(max_length=50, null=True)),
                ("wtsk_to_loc", models.CharField(max_length=50, null=True)),
                ("wtsk_qty_exp", models.CharField(max_length=50, null=True)),
                ("wtsk_create_date", models.CharField(max_length=50, null=True)),
                ("wtsk_create_time", models.CharField(max_length=50, null=True)),
                ("timestamp", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Fa Supply Items",
                "verbose_name_plural": "Fa Supply Items",
                "managed": True,
            },
        ),
    ]
