"""
Django settings for vproject project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "nrne*&c_e7d1goipgpk%!s@n9djg=@m*kd!*f@&y#4g77*&xg("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "136.16.181.132",
    "10.116.180.157",
    "136.16.181.132:8001",
    "136.16.180.151:8080",
    "136.16.180.177",
    "136.16.180.177:8000",
    "136.16.180.151:8097",
    "136.16.180.151",
    "localhost",
    "0.0.0.0",
    "*",
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# Application definition

INSTALLED_APPS = [
    "main",
    "vware",
    "accounts",
    "pManagement",
    "crossdocking.apps.CrossdockingConfig",
    "shippers",
    "inqueritos",
    "receiving.apps.ReceivingConfig",
    "qad_ee",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    "crispy_forms",
    "widget_tweaks",
    "pedro_test",
]

SCHEDULER_DEFAULT = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vproject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "sql_server.pyodbc",
        "NAME": "visteon2",
        "USER": "Aroque1",
        "PASSWORD": "Django1django",
        "HOST": "PTD6NJ8CT1\SQLEXPRESS",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "qad_ee": {
        "ENGINE": "sql_server.pyodbc",
        "NAME": "QAD_EE",
        "USER": "pwms_read",
        "PASSWORD": "Pass@4321",
        "HOST": "GLCDV262\PRO2",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
}


DATABASE_ROUTERS = [
    "routers.db_routers.DefaultRouter",
    "routers.db_routers.Qad_EERouter",
]

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "Europe/Lisbon"

USE_I18N = False

USE_L10N = False

USE_TZ = False

CRISPY_TEMPLATE_PACK = "bootstrap4"

DATE_FORMAT = "Y-m-d"
DATE_INPUT_FORMAT = ["%Y-%m-%d"]
DATETIME_FORMAT = "Y-m-d H:i"
DATETIME_INPUT_FORMATS = [
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30:59'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
LOGIN_REDIRECT_URL = "home"
LOGIN_URL = "/accounts/login"

# EMAIL SETTINGS
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "vistsmtp.visteon.com"
EMAIL_HOST_USER = "noreply@visteon.com"
EMAIL_PORT = 25
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = "noreply@visteon.com"
SERVER_EMAIL = "noreply@visteon.com"

CELERY_TIMEZONE = "Europe/London"
