# Generated by Django 4.1.5 on 2023-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crossdocking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDiarioSchedule_view",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.CharField(max_length=50, null=True)),
                ("site", models.CharField(max_length=50, null=True)),
                ("due_date", models.CharField(max_length=50, null=True)),
                ("item_number", models.CharField(max_length=50, null=True)),
                ("to_complete", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("qty_completed", models.CharField(max_length=50, null=True)),
                ("timeStamp", models.CharField(max_length=200, null=True)),
            ],
            options={
                "db_table": "informacao_email_schedule",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmailDiarioInformacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ficheiro",
                    models.FileField(null=True, upload_to="ConfigurationsEmail/"),
                ),
                (
                    "data_guardado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailDiarioSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.CharField(max_length=50, null=True)),
                ("site", models.CharField(max_length=50, null=True)),
                ("due_date", models.CharField(max_length=50, null=True)),
                ("item_number", models.CharField(max_length=50, null=True)),
                ("to_complete", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("qty_completed", models.CharField(max_length=50, null=True)),
                ("timeStamp", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
