# Generated by Django 2.1.15 on 2022-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayContactoCondutor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
