# Generated by Django 3.0.7 on 2022-10-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingpage',
            name='qtyCaixas',
        ),
    ]
