# Generated by Django 2.1.15 on 2022-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0002_gatewaycontactocondutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="contacto",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
