# Generated by Django 3.0.7 on 2022-10-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0002_remove_trackingpage_qtycaixas'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpage',
            name='qtyCaixas',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
