# Generated by Django 4.1.5 on 2023-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0002_tracking_shipperspage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_shipperspage",
            name="vehicle_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
