# Generated by Django 4.1.5 on 2023-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0003_alter_tracking_shipperspage_vehicle_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_shipperspage",
            name="estado",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
