# Generated by Django 3.0.7 on 2022-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0003_trackingpage_qtycaixas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpage',
            name='inicioPrep',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
