# Generated by Django 3.0.7 on 2022-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0004_auto_20221010_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='dataHoraCarga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
