# Generated by Django 4.1.5 on 2023-03-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0005_tracking_shipperspage_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tracking_ShippersPage",
        ),
    ]
