# Generated by Django 2.1.15 on 2022-03-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0005_auto_20220310_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaycondutor",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shippers.GatewayEmpresa",
            ),
        ),
        migrations.AddField(
            model_name="gatewaycondutorid",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shippers.GatewayEmpresa",
            ),
        ),
        migrations.AddField(
            model_name="gatewaycontactocondutor",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shippers.GatewayEmpresa",
            ),
        ),
        migrations.AddField(
            model_name="gatewayprimeiramatricula",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shippers.GatewayEmpresa",
            ),
        ),
    ]
