# Generated by Django 4.1.5 on 2023-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0006_delete_tracking_shipperspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracking_ShippersPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abs_id", models.CharField(max_length=200, null=True)),
                ("ship_date", models.CharField(max_length=200, null=True)),
                ("ship_time", models.CharField(max_length=200, null=True)),
                ("city", models.CharField(max_length=200, null=True)),
                ("country", models.CharField(max_length=200, null=True)),
                ("carrier", models.CharField(max_length=200, null=True)),
                ("fob", models.CharField(max_length=200, null=True)),
                ("mode_of_transport", models.CharField(max_length=200, null=True)),
                ("vehicle_id", models.CharField(max_length=200, null=True)),
                ("total_master_packs", models.CharField(max_length=200, null=True)),
                ("confirmed", models.CharField(max_length=200, null=True)),
                ("estado", models.CharField(max_length=50, null=True)),
                ("timestamp", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
