# Generated by Django 2.1.15 on 2022-03-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0007_gatewayinfocondutor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatewaycondutor",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="gatewaycondutorid",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="gatewaycontactocondutor",
            name="empresa",
        ),
    ]
