# Generated by Django 2.1.15 on 2022-03-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0008_auto_20220311_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewayinfocondutor",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shippers.GatewayEmpresa",
            ),
        ),
    ]
