# Generated by Django 2.1.15 on 2022-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0009_gatewayinfocondutor_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="estadoDataHoraEntrada",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="estadoDataHoraSaida",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
