# Generated by Django 4.1.5 on 2023-04-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0009_updatesproj"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MediaMensalEmpresa",
        ),
        migrations.DeleteModel(
            name="MediaTotalPortaria",
        ),
        migrations.DeleteModel(
            name="NumeroHorasEmailDiario",
        ),
        migrations.AddField(
            model_name="tracking_shipperspage",
            name="comentarios",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="comentEntrada",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="comentSaida",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="gatewaybackup",
            name="comentEntrada",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="gatewaybackup",
            name="comentSaida",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="trackingpage",
            name="inicioPrep",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
