# Generated by Django 2.1.15 on 2022-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0010_auto_20220314_1321"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gateway",
            name="estadoDataHoraEntrada",
        ),
        migrations.RemoveField(
            model_name="gateway",
            name="estadoDataHoraSaida",
        ),
    ]
