# Generated by Django 4.1.5 on 2023-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shippers",
            "0010_delete_mediamensalempresa_delete_mediatotalportaria_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_shipperspage",
            name="comentarios",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
