# Generated by Django 4.1.5 on 2023-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0011_alter_tracking_shipperspage_comentarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracking_shipperspage",
            name="comentarios",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
