# Generated by Django 2.1.15 on 2022-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0011_auto_20220315_0902"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiltrarBotoes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entrada", models.CharField(max_length=100, null=True)),
                ("saida", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
