# Generated by Django 4.1.5 on 2023-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0012_alter_tracking_shipperspage_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_shipperspage",
            name="date_Validation",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
