# Generated by Django 3.0.7 on 2022-04-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0012_filtrarbotoes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FiltrarBotoes",
        ),
    ]
