# Generated by Django 4.1.5 on 2023-04-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0013_tracking_shipperspage_date_validation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracking_shipperspage",
            old_name="date_Validation",
            new_name="date_validation",
        ),
    ]
