# Generated by Django 3.0.7 on 2022-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0013_delete_filtrarbotoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayBackup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataHoraChegada", models.CharField(max_length=100, null=True)),
                ("empresa", models.CharField(max_length=100, null=True)),
                ("condutor", models.CharField(max_length=100, null=True)),
                ("ident", models.CharField(max_length=100, null=True)),
                ("contacto", models.CharField(max_length=100, null=True)),
                ("primeiraMatricula", models.CharField(max_length=100, null=True)),
                ("segundaMatricula", models.CharField(max_length=100, null=True)),
                ("cargaDescarga", models.CharField(max_length=100, null=True)),
                ("doca", models.CharField(max_length=100, null=True)),
                ("destinoCarga", models.CharField(max_length=100, null=True)),
                ("tipoViatura", models.CharField(max_length=100, null=True)),
                ("dataHoraEntrada", models.CharField(max_length=100, null=True)),
                ("estado", models.CharField(max_length=100, null=True)),
                ("abandono", models.CharField(max_length=100, null=True)),
                ("comentEntrada", models.CharField(max_length=300, null=True)),
                ("dataHoraSaida", models.CharField(max_length=100, null=True)),
                ("comentSaida", models.CharField(max_length=300, null=True)),
            ],
            options={
                "verbose_name": "Gateway histórico - BACKUP",
                "verbose_name_plural": "Gateway histórico - BACKUP",
                "managed": True,
            },
        ),
    ]
