# Generated by Django 4.1.5 on 2023-04-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "shippers",
            "0014_rename_date_validation_tracking_shipperspage_date_validation",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracking_shipperspage",
            name="total_master_packs",
        ),
    ]
