# Generated by Django 3.0.7 on 2022-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0014_gatewaybackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nShipper', models.CharField(max_length=100, null=True)),
                ('incioPrep', models.DateField()),
                ('fimPrep', models.DateField()),
                ('confirmacao', models.DateField()),
                ('comentarios', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
