# Generated by Django 3.0.7 on 2022-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0015_trackingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpage',
            name='qtyCaixas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpage',
            name='confirmacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trackingpage',
            name='fimPrep',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trackingpage',
            name='incioPrep',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trackingpage',
            name='nShipper',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
