# Generated by Django 4.1.5 on 2023-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shippers", "0015_remove_tracking_shipperspage_total_master_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracking_shipperspage",
            name="total_master_packs",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
