# Generated by Django 3.0.7 on 2022-09-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0017_auto_20220908_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingpage',
            old_name='incioPrep',
            new_name='inicioPrep',
        ),
    ]
