# Generated by Django 3.0.7 on 2022-09-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0018_auto_20220909_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpage',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpage',
            name='nShipper',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
