# Generated by Django 3.0.7 on 2022-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0020_auto_20220912_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpage',
            name='qtyCaixas',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
