# Generated by Django 3.0.7 on 2022-09-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0021_auto_20220913_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingpage',
            options={'managed': False},
        ),
    ]
