# Generated by Django 3.0.7 on 2022-09-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0022_auto_20220919_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingpage',
            options={},
        ),
    ]
