# Generated by Django 3.0.7 on 2022-09-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0023_auto_20220919_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingpage',
            options={'managed': False},
        ),
    ]
