# Generated by Django 3.0.7 on 2022-09-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0024_auto_20220919_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackingpage',
            table='sct_det',
        ),
    ]
