# Generated by Django 3.0.7 on 2022-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0025_auto_20220919_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sct_Det_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prrowid', models.CharField(db_column='prrowid', max_length=36)),
                ('sct_sim', models.CharField(db_column='sct_sim', max_length=36)),
            ],
            options={
                'db_table': 'sct_det',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='trackingpage',
            options={},
        ),
    ]
