# Generated by Django 3.0.7 on 2022-09-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0026_auto_20220919_1601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sct_det_view',
            table='SctDet',
        ),
        migrations.AlterModelTable(
            name='trackingpage',
            table=None,
        ),
    ]
