# Generated by Django 3.0.7 on 2022-09-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0027_auto_20220919_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sct_det_view',
            table='sct_det',
        ),
    ]
