# Generated by Django 3.0.7 on 2022-09-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0028_auto_20220919_1620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sct_det_view',
            table='qad_ee',
        ),
    ]
