# Generated by Django 3.0.7 on 2022-09-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0029_auto_20220919_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sct_Det_View',
        ),
    ]
