# Generated by Django 3.0.7 on 2022-09-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0031_sct_det_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sct_det_view',
            table='sct_det',
        ),
    ]
