# Generated by Django 3.1 on 2022-12-16 09:34

from django.db import migrations, models
import django.db.models.deletion
import vware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmazemChecklistQPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(choices=[('PSA', 'PSA'), ('DAIMLER', 'DAIMLER'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('JLR', 'JLR'), ('PORSCHE', 'PORSCHE'), ('RENAULT', 'RENAULT'), ('SKODA | VOLKWAGEN', 'SKODA | VOLKWAGEN'), ('SCANIA', 'SCANIA'), ('VOLVO', 'VOLVO'), ('MASERATI', 'MASERATI')], max_length=40, unique=True)),
                ('qpsShipping', models.FileField(blank='true', null='true', upload_to='qpsShipping/')),
                ('qpsPacking', models.FileField(blank='true', null='true', upload_to='qpsPacking/')),
                ('checklist', models.FileField(blank='true', null='true', upload_to='checklist/')),
                ('inspecaoDedicada', models.FileField(blank='true', null='true', upload_to='procInspDelicado/')),
                ('crossDocking', models.FileField(blank='true', null='true', upload_to='crossDocking/')),
                ('engenharia', models.FileField(blank='true', null='true', upload_to='e  ngenharia/')),
                ('servicos', models.FileField(blank='true', null='true', upload_to='servicos/')),
                ('guideLines', models.FileField(blank='true', null='true', upload_to='guideLines/')),
            ],
            options={
                'verbose_name': 'Clientes Shipping',
                'verbose_name_plural': 'Clientes Shipping',
            },
        ),
        migrations.CreateModel(
            name='ClientesOEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Clientes_OEM',
                'verbose_name_plural': 'Clientes_OEM',
            },
        ),
        migrations.CreateModel(
            name='Crossdocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ford', models.FileField(blank='true', null='true', upload_to='crossdocking/ford/')),
                ('psa', models.FileField(blank='true', null='true', upload_to='crossdocking/psa/')),
                ('scania', models.FileField(blank='true', null='true', upload_to='crossdocking/scania/')),
                ('volvo', models.FileField(blank='true', null='true', upload_to='crossdocking/volvo/')),
            ],
            options={
                'verbose_name': 'Crossdocking',
                'verbose_name_plural': 'Crossdocking',
            },
        ),
        migrations.CreateModel(
            name='LinksShippingOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(max_length=150)),
                ('link2', models.CharField(max_length=150)),
                ('link3', models.CharField(max_length=150)),
                ('link4', models.CharField(max_length=150)),
                ('link5', models.CharField(max_length=150)),
                ('link6', models.CharField(max_length=150)),
                ('link7', models.CharField(max_length=150)),
                ('link8', models.CharField(max_length=150)),
                ('others', models.CharField(max_length=150)),
                ('requestShippers', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Link Operation',
                'verbose_name_plural': 'Link Operation',
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.FileField(blank='true', null='true', upload_to='others/one/')),
                ('two', models.FileField(blank='true', null='true', upload_to='others/two/')),
                ('three', models.FileField(blank='true', null='true', upload_to='others/three/')),
                ('four', models.FileField(blank='true', null='true', upload_to='others/four/')),
                ('five', models.FileField(blank='true', null='true', upload_to='others/five/')),
            ],
            options={
                'verbose_name': 'Others',
                'verbose_name_plural': 'Others',
            },
        ),
        migrations.CreateModel(
            name='Procedimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docOne', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/one/')),
                ('docTwo', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/two/')),
                ('docThree', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/three/')),
                ('docFour', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/four/')),
                ('docFive', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/five/')),
                ('docSix', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/six/')),
                ('docSeven', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/seven/')),
                ('docEight', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/eight/')),
                ('docNine', models.FileField(blank='true', null='true', upload_to='procedimentos/documentacao/nine/')),
                ('anexoOne', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/one/')),
                ('anexoTwo', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/two/')),
                ('anexoThree', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/three/')),
                ('anexoFour', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/four/')),
                ('anexoFive', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/five/')),
                ('anexoSix', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/six/')),
                ('anexoSeven', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/seven/')),
                ('anexoEight', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/eight/')),
                ('anexoNine', models.FileField(blank='true', null='true', upload_to='procedimentos/anexos/nine/')),
                ('qpsOne', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/one/')),
                ('qpsTwo', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/two/')),
                ('qpsThree', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/three/')),
                ('qpsFour', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/four/')),
                ('qpsFive', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/five/')),
                ('qpsSix', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/six/')),
                ('qpsSeven', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/seven/')),
                ('qpsEight', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/eight/')),
                ('qpsNine', models.FileField(blank='true', null='true', upload_to='procedimentos/qps/nine/')),
            ],
            options={
                'verbose_name': 'Procedimentos',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Prodlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Prodline',
                'verbose_name_plural': 'Prodline',
            },
        ),
        migrations.CreateModel(
            name='ReceivingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.FileField(blank='true', null='true', upload_to='receiving/one/')),
                ('two', models.FileField(blank='true', null='true', upload_to='receiving/two/')),
                ('three', models.FileField(blank='true', null='true', upload_to='receiving/three/')),
                ('four', models.FileField(blank='true', null='true', upload_to='receiving/four/')),
                ('five', models.FileField(blank='true', null='true', upload_to='receiving/five/')),
                ('six', models.FileField(blank='true', null='true', upload_to='receiving/six/')),
                ('seven', models.FileField(blank='true', null='true', upload_to='receiving/seven/')),
                ('eight', models.FileField(blank='true', null='true', upload_to='receiving/eight/')),
                ('nine', models.FileField(blank='true', null='true', upload_to='receiving/nine/')),
            ],
            options={
                'verbose_name': 'Receiving Operation',
                'verbose_name_plural': 'Receiving Operation',
            },
        ),
        migrations.CreateModel(
            name='ShippingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.FileField(blank='true', null='true', upload_to='shipping/one/')),
                ('two', models.FileField(blank='true', null='true', upload_to='shipping/two/')),
                ('three', models.FileField(blank='true', null='true', upload_to='shipping/three/')),
                ('four', models.FileField(blank='true', null='true', upload_to='shipping/four/')),
                ('five', models.FileField(blank='true', null='true', upload_to='shipping/five/')),
                ('six', models.FileField(blank='true', null='true', upload_to='shipping/six/')),
                ('seven', models.FileField(blank='true', null='true', upload_to='shipping/seven/')),
                ('eight', models.FileField(blank='true', null='true', upload_to='shipping/eight/')),
                ('checklist', models.FileField(blank='true', null='true', upload_to='shipping/checklist/')),
                ('others', models.FileField(blank='true', null='true', upload_to='shipping/others/')),
                ('requestShippers', models.FileField(blank='true', null='true', upload_to='shipping/requestShippers/')),
            ],
            options={
                'verbose_name': 'Shipping Operation',
                'verbose_name_plural': 'Shipping Operation',
            },
        ),
        migrations.CreateModel(
            name='SupplyPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('description', models.CharField(blank='true', max_length=255, null=True)),
                ('comment', models.CharField(blank='true', max_length=255, null=True)),
                ('supply_time', models.IntegerField(blank='true', default=60, null=True)),
                ('stock', models.IntegerField(blank='true', default=0, null=True)),
                ('inventario', models.IntegerField(blank='true', default=0, null=True)),
                ('link', models.FileField(blank='true', max_length=200, null='true', upload_to='SupplyPackage/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmbalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank='true', default=0, null=True)),
                ('tempoSupply', models.IntegerField(blank='true', default=60, null=True)),
                ('link', models.FileField(blank='true', null='true', upload_to='embalagemLink/')),
            ],
            options={
                'verbose_name': 'Tipo embalagem',
                'verbose_name_plural': 'Tipo embalagem',
            },
        ),
        migrations.CreateModel(
            name='StockPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(db_index=True, max_length=50)),
                ('descricao', models.CharField(max_length=150, null=True)),
                ('link', models.FileField(null=True, upload_to='StockPackage/')),
                ('quantidade', models.CharField(max_length=50, null=True)),
                ('inventario', models.CharField(max_length=50, null=True)),
                ('comentario', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(choices=[(vware.models.PackageType['EXP'], 'Expendable'), (vware.models.PackageType['RET'], 'Returnable')], default=None, max_length=20)),
                ('suplyPackage', models.ManyToManyField(to='vware.SupplyPackage')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vware.clientesoem')),
                ('tipo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vware.tipoembalagem')),
            ],
            options={
                'verbose_name': 'Produtos',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='clientesoem',
            name='suplyPackage',
            field=models.ManyToManyField(to='vware.SupplyPackage'),
        ),
        migrations.CreateModel(
            name='ClienteProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vware.clientesoem')),
                ('produto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vware.produtos')),
                ('supply_pkg', models.ManyToManyField(to='vware.SupplyPackage')),
            ],
        ),
    ]
