# Generated by Django 3.0.7 on 2022-08-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vware.ClientesOEM'),
        ),
        migrations.AlterField(
            model_name='clientesoem',
            name='suplyPackage',
            field=models.ManyToManyField(to='vware.SupplyPackage'),
        ),
        migrations.AlterField(
            model_name='stockpackage',
            name='suplyPackage',
            field=models.ManyToManyField(to='vware.SupplyPackage'),
        ),
    ]
