# Generated by Django 3.0.7 on 2022-08-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0002_clienteproduto_supplypackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteproduto',
            name='supplyPackage',
        ),
        migrations.AddField(
            model_name='supplypackage',
            name='cliente_produto',
            field=models.ForeignKey(blank='true', default=None, null='true', on_delete=django.db.models.deletion.CASCADE, to='vware.ClienteProduto'),
            preserve_default='true',
        ),
    ]
