# Generated by Django 3.0.7 on 2022-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0002_auto_20220803_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='comentario',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
