# Generated by Django 3.0.7 on 2022-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0003_auto_20220818_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplypackage',
            name='cliente_produto',
        ),
        migrations.AddField(
            model_name='clienteproduto',
            name='supply_pkg',
            field=models.ManyToManyField(to='vware.SupplyPackage'),
        ),
    ]
