# Generated by Django 3.0.7 on 2022-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0004_auto_20220803_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='cliente',
        ),
        migrations.AddField(
            model_name='clientesoem',
            name='produto',
            field=models.ManyToManyField(to='vware.Produtos'),
        ),
    ]
