# Generated by Django 3.0.7 on 2022-08-31 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0004_auto_20220822_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vware.ClientesOEM'),
        ),
    ]
