# Generated by Django 3.0.7 on 2022-08-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vware', '0005_auto_20220804_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesoem',
            name='produto',
        ),
        migrations.CreateModel(
            name='ClienteProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
                ('comment', models.CharField(max_length=40, unique=True)),
                ('client_name', models.ForeignKey(blank='true', default=None, null='true', on_delete=django.db.models.deletion.CASCADE, to='vware.ClientesOEM')),
                ('product_name', models.ForeignKey(blank='true', default=None, null='true', on_delete=django.db.models.deletion.CASCADE, to='vware.Produtos')),
                ('suplyPackage', models.ManyToManyField(to='vware.SupplyPackage')),
            ],
            options={
                'verbose_name': 'ClienteProduto',
                'verbose_name_plural': 'ClienteProduto',
            },
        ),
    ]
