# Generated by Django 2.1.15 on 2022-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qad_ee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WoMstr",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prrowid", models.CharField(max_length=36)),
                ("wo_nbr", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_lot", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_so_job", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_ord_date", models.DateTimeField(blank=True, null=True)),
                ("wo_rel_date", models.DateTimeField(blank=True, null=True)),
                ("wo_due_date", models.DateTimeField(blank=True, null=True)),
                ("wo_per_date", models.DateTimeField(blank=True, null=True)),
                ("wo_part", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_type", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "wo_qty_ord",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_qty_comp",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_qty_rjct",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_status", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_vend", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_rmks", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_qty_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_rjct_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_bo_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_yield_pct",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_rev", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_acct", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_qad01",
                    models.CharField(
                        blank=True, db_column="wo__qad01", max_length=80, null=True
                    ),
                ),
                ("wo_lot_prev", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_schd_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("wo_cmtindx", models.IntegerField(blank=True, null=True)),
                ("wo_project", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_lead_time", models.IntegerField(blank=True, null=True)),
                (
                    "wo_wip_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_lbr_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_mtl_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_bdn_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_sub_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_user1", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_user2", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_ovh_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_loc", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_serial", models.CharField(blank=True, max_length=50, null=True)),
                ("wo_routing", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_bom_code", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_site", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_queue_eff",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_draw", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_lbr_up", models.BooleanField(blank=True, null=True)),
                ("wo_bdn_up", models.BooleanField(blank=True, null=True)),
                ("wo_gl_lbr", models.BooleanField(blank=True, null=True)),
                ("wo_gl_bdn", models.BooleanField(blank=True, null=True)),
                (
                    "wo_chr01",
                    models.CharField(
                        blank=True, db_column="wo__chr01", max_length=80, null=True
                    ),
                ),
                (
                    "wo_chr02",
                    models.CharField(
                        blank=True, db_column="wo__chr02", max_length=80, null=True
                    ),
                ),
                (
                    "wo_chr03",
                    models.CharField(
                        blank=True, db_column="wo__chr03", max_length=80, null=True
                    ),
                ),
                (
                    "wo_chr04",
                    models.CharField(
                        blank=True, db_column="wo__chr04", max_length=80, null=True
                    ),
                ),
                (
                    "wo_chr05",
                    models.CharField(
                        blank=True, db_column="wo__chr05", max_length=80, null=True
                    ),
                ),
                (
                    "wo_dte01",
                    models.DateTimeField(blank=True, db_column="wo__dte01", null=True),
                ),
                (
                    "wo_dte02",
                    models.DateTimeField(blank=True, db_column="wo__dte02", null=True),
                ),
                (
                    "wo_dec01",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__dec01",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_dec02",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__dec02",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_log01",
                    models.BooleanField(blank=True, db_column="wo__log01", null=True),
                ),
                ("wo_line", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_var", models.BooleanField(blank=True, null=True)),
                (
                    "wo_mtl_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_lbr_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_bdn_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_sub_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_mvar_acct",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("wo_mvar_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_mvrr_acct",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("wo_mvrr_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_svar_acct",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("wo_svar_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_svrr_acct",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("wo_svrr_cc", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_flr_acct", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_flr_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_dec03",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__dec03",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_rjct_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_mthd_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_rval_tot",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_acct_close", models.BooleanField(blank=True, null=True)),
                ("wo_close_date", models.DateTimeField(blank=True, null=True)),
                ("wo_close_eff", models.DateTimeField(blank=True, null=True)),
                ("wo_fsm_type", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_xvar_acct",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("wo_xvar_cc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "wo_myld_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_joint_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "wo_prod_pct",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_qty_type", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "wo_dec04",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__dec04",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                ("wo_base_id", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "wo_unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_mix_var",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_bdn_totx",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_lbr_totx",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_mtl_totx",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_sub_totx",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_ovh_totx",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_rctstat_active", models.BooleanField(blank=True, null=True)),
                ("wo_batch", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "wo_assay",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_grade", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_expire", models.DateTimeField(blank=True, null=True)),
                ("wo_rctstat", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_lot_next", models.CharField(blank=True, max_length=30, null=True)),
                ("wo_lot_rcpt", models.BooleanField(blank=True, null=True)),
                (
                    "wo_ca_int_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("wo_iss_site", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_itm_line", models.IntegerField(blank=True, null=True)),
                ("wo_date_posted", models.DateTimeField(blank=True, null=True)),
                (
                    "wo_qadc01",
                    models.CharField(
                        blank=True, db_column="wo__qadc01", max_length=80, null=True
                    ),
                ),
                (
                    "wo_qadc02",
                    models.CharField(
                        blank=True, db_column="wo__qadc02", max_length=80, null=True
                    ),
                ),
                (
                    "wo_qadc03",
                    models.CharField(
                        blank=True, db_column="wo__qadc03", max_length=80, null=True
                    ),
                ),
                (
                    "wo_qadt01",
                    models.DateTimeField(blank=True, db_column="wo__qadt01", null=True),
                ),
                (
                    "wo_qadt02",
                    models.DateTimeField(blank=True, db_column="wo__qadt02", null=True),
                ),
                (
                    "wo_qade01",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__qade01",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_qade02",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__qade02",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_qade03",
                    models.DecimalField(
                        blank=True,
                        db_column="wo__qade03",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "wo_qadi01",
                    models.IntegerField(blank=True, db_column="wo__qadi01", null=True),
                ),
                (
                    "wo_qadi02",
                    models.IntegerField(blank=True, db_column="wo__qadi02", null=True),
                ),
                (
                    "wo_qadl01",
                    models.BooleanField(blank=True, db_column="wo__qadl01", null=True),
                ),
                (
                    "wo_qadl02",
                    models.BooleanField(blank=True, db_column="wo__qadl02", null=True),
                ),
                ("wo_eng_code", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_flr_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_mvar_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_mvrr_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_svar_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_svrr_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_xvar_sub", models.CharField(blank=True, max_length=20, null=True)),
                ("wo_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("wo_record_date", models.DateTimeField(blank=True, null=True)),
                ("wo_stat_close_date", models.DateTimeField(blank=True, null=True)),
                (
                    "wo_stat_close_userid",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "wo_app_owner",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("wo_domain", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "oid_wo_mstr",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_doc_id", models.CharField(blank=True, max_length=24, null=True)),
                (
                    "wo_rate",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_selected_for_print", models.BooleanField(blank=True, null=True)),
                (
                    "wo_seq",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("wo_shift", models.CharField(blank=True, max_length=2, null=True)),
                ("wo_order_sheet_printed", models.BooleanField(blank=True, null=True)),
                ("wo_setup_time", models.IntegerField(blank=True, null=True)),
                ("wo_due_date_anchor", models.BooleanField(blank=True, null=True)),
                ("wo_tool", models.CharField(blank=True, max_length=8, null=True)),
                ("wo_run_size", models.IntegerField(blank=True, null=True)),
                (
                    "wo_nbr_lines",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("wo_duration_buffer", models.IntegerField(blank=True, null=True)),
                ("wo_qty_booked", models.IntegerField(blank=True, null=True)),
                ("wo_need_date", models.DateTimeField(blank=True, null=True)),
                ("wo_priority", models.IntegerField(blank=True, null=True)),
                (
                    "wo_restriction",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("wo_allow_splits", models.BooleanField(blank=True, null=True)),
                (
                    "wo_qty_exp_complete",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_qty_exp_scrap",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("wo_mfg_type", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "wo_cum_lot_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("wo_need_time", models.IntegerField(blank=True, null=True)),
                ("wo_mps_auto_reschedule", models.BooleanField(blank=True, null=True)),
                (
                    "oid_wo_demand",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "wo_demand_dataset",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "pro2srcpdb",
                    models.CharField(
                        blank=True, db_column="Pro2SrcPDB", max_length=12, null=True
                    ),
                ),
                ("pro2created", models.DateTimeField(blank=True, null=True)),
                ("pro2modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wo_mstr",
                "managed": False,
            },
        ),
    ]
