# Generated by Django 2.1.15 on 2022-03-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qad_ee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbscDet',
        ),
        migrations.DeleteModel(
            name='AbsMstr',
        ),
        migrations.DeleteModel(
            name='AdMstr',
        ),
    ]
