# Generated by Django 3.0.7 on 2022-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qad_ee", "0002_womstr"),
    ]

    operations = [
        migrations.CreateModel(
            name="InMstr",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prrowid", models.CharField(max_length=36)),
                ("in_part", models.CharField(blank=True, max_length=30, null=True)),
                ("in_site", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "in_qty_oh",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_qty_req",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_qty_all",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_qty_ord",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_qty_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_qty_avail",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_sls_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_iss_chg",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("in_iss_date", models.DateTimeField(blank=True, null=True)),
                ("in_rec_date", models.DateTimeField(blank=True, null=True)),
                ("in_cnt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "in_avg_iss",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_avg_sls",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("in_avg_date", models.DateTimeField(blank=True, null=True)),
                ("in_user1", models.CharField(blank=True, max_length=80, null=True)),
                ("in_user2", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "in_rop",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "in_sfty_stk",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "in_qty_nonet",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("in_mrp", models.BooleanField(blank=True, null=True)),
                ("in_gl_set", models.CharField(blank=True, max_length=80, null=True)),
                ("in_cur_set", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "in_qadc02",
                    models.CharField(
                        blank=True, db_column="in__qadc02", max_length=80, null=True
                    ),
                ),
                (
                    "in_qadi01",
                    models.IntegerField(blank=True, db_column="in__qadi01", null=True),
                ),
                (
                    "in_qadi02",
                    models.IntegerField(blank=True, db_column="in__qadi02", null=True),
                ),
                ("in_level", models.IntegerField(blank=True, null=True)),
                ("in_loc", models.CharField(blank=True, max_length=80, null=True)),
                ("in_loc_type", models.CharField(blank=True, max_length=80, null=True)),
                ("in_proj_use", models.IntegerField(blank=True, null=True)),
                ("in_grade", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "in_assay",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("in_rollup", models.BooleanField(blank=True, null=True)),
                (
                    "in_rollup_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "in_qadc03",
                    models.CharField(
                        blank=True, db_column="in__qadc03", max_length=80, null=True
                    ),
                ),
                (
                    "in_qadc04",
                    models.CharField(
                        blank=True, db_column="in__qadc04", max_length=80, null=True
                    ),
                ),
                (
                    "in_qadl01",
                    models.BooleanField(blank=True, db_column="in__qadl01", null=True),
                ),
                (
                    "in_qadl02",
                    models.BooleanField(blank=True, db_column="in__qadl02", null=True),
                ),
                (
                    "in_qadc01",
                    models.CharField(
                        blank=True, db_column="in__qadc01", max_length=80, null=True
                    ),
                ),
                ("in_wh", models.BooleanField(blank=True, null=True)),
                (
                    "in_gl_cost_site",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "in_cust_consign_qty",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "in_supp_consign_qty",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("in_domain", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "oid_in_mstr",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "pro2srcpdb",
                    models.CharField(
                        blank=True, db_column="Pro2SrcPDB", max_length=12, null=True
                    ),
                ),
                ("pro2created", models.DateTimeField(blank=True, null=True)),
                ("pro2modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "in_mstr",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LdDet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prrowid", models.CharField(max_length=36)),
                ("ld_loc", models.CharField(blank=True, max_length=80, null=True)),
                ("ld_part", models.CharField(blank=True, max_length=30, null=True)),
                ("ld_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ld_qty_oh",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_lot", models.CharField(blank=True, max_length=30, null=True)),
                ("ld_ref", models.CharField(blank=True, max_length=80, null=True)),
                ("ld_cnt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ld_assay",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_expire", models.DateTimeField(blank=True, null=True)),
                ("ld_user1", models.CharField(blank=True, max_length=80, null=True)),
                ("ld_user2", models.CharField(blank=True, max_length=80, null=True)),
                ("ld_site", models.CharField(blank=True, max_length=80, null=True)),
                ("ld_status", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "ld_qty_all",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_grade", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "ld_qty_frz",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_date_frz", models.DateTimeField(blank=True, null=True)),
                ("ld_vd_lot", models.CharField(blank=True, max_length=30, null=True)),
                ("ld_cmtindx", models.IntegerField(blank=True, null=True)),
                (
                    "ld_work",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ld_chr01",
                    models.CharField(
                        blank=True, db_column="ld__chr01", max_length=80, null=True
                    ),
                ),
                (
                    "ld_chr02",
                    models.CharField(
                        blank=True, db_column="ld__chr02", max_length=80, null=True
                    ),
                ),
                (
                    "ld_chr03",
                    models.CharField(
                        blank=True, db_column="ld__chr03", max_length=80, null=True
                    ),
                ),
                (
                    "ld_chr04",
                    models.CharField(
                        blank=True, db_column="ld__chr04", max_length=80, null=True
                    ),
                ),
                (
                    "ld_chr05",
                    models.CharField(
                        blank=True, db_column="ld__chr05", max_length=80, null=True
                    ),
                ),
                (
                    "ld_dte01",
                    models.DateTimeField(blank=True, db_column="ld__dte01", null=True),
                ),
                (
                    "ld_dte02",
                    models.DateTimeField(blank=True, db_column="ld__dte02", null=True),
                ),
                (
                    "ld_dec01",
                    models.DecimalField(
                        blank=True,
                        db_column="ld__dec01",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "ld_dec02",
                    models.DecimalField(
                        blank=True,
                        db_column="ld__dec02",
                        decimal_places=10,
                        max_digits=38,
                        null=True,
                    ),
                ),
                (
                    "ld_log01",
                    models.BooleanField(blank=True, db_column="ld__log01", null=True),
                ),
                (
                    "ld_cost",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_rev", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "ld_cust_consign_qty",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ld_supp_consign_qty",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_domain", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "oid_ld_det",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_alt_um", models.CharField(blank=True, max_length=30, null=True)),
                ("ld_crt_time", models.IntegerField(blank=True, null=True)),
                ("ld_crt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ld_exp_qtyin",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ld_exp_qtyout",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ld_time_frz", models.IntegerField(blank=True, null=True)),
                (
                    "pro2srcpdb",
                    models.CharField(
                        blank=True, db_column="Pro2SrcPDB", max_length=12, null=True
                    ),
                ),
                ("pro2created", models.DateTimeField(blank=True, null=True)),
                ("pro2modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ld_det",
                "managed": False,
            },
        ),
    ]
