# Generated by Django 3.0.7 on 2022-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qad_ee", "0003_inmstr_lddet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SerMstr",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prrowid", models.CharField(max_length=36)),
                ("ser_domain", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "ser_serial_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "oid_ser_mstr_parent",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ser_stage", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ser_pack_code",
                    models.CharField(blank=True, max_length=18, null=True),
                ),
                ("ser_prt_lbl", models.BooleanField(blank=True, null=True)),
                (
                    "oid_loc_mstr",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ser_site", models.CharField(blank=True, max_length=80, null=True)),
                ("ser_loc", models.CharField(blank=True, max_length=30, null=True)),
                ("ser_part", models.CharField(blank=True, max_length=30, null=True)),
                ("ser_lotser", models.CharField(blank=True, max_length=30, null=True)),
                ("ser_ref", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "ser_qty_pck",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ser_qty_avail",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ser_um", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "ser_mod_userid",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("ser_mod_date", models.DateTimeField(blank=True, null=True)),
                ("ser_user1", models.CharField(blank=True, max_length=80, null=True)),
                ("ser_user2", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "ser_qadc01",
                    models.CharField(
                        blank=True, db_column="ser__qadc01", max_length=80, null=True
                    ),
                ),
                (
                    "ser_qadc02",
                    models.CharField(
                        blank=True, db_column="ser__qadc02", max_length=80, null=True
                    ),
                ),
                (
                    "oid_ser_mstr",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ser_ship_wt",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ser_ship_wt_um",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "ser_size",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                ("ser_size_um", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "oid_ld_det",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                ("ser_truck_loaded", models.BooleanField(blank=True, null=True)),
                (
                    "ser_gross_weight",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=38, null=True
                    ),
                ),
                (
                    "ser_gross_weight_um",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("ser_unloaded", models.BooleanField(blank=True, null=True)),
                ("ser_phantom", models.BooleanField(blank=True, null=True)),
                (
                    "ser_vend_lot",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "ser_ext_sn_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("ser_commission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ser_origin_code",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "pro2srcpdb",
                    models.CharField(
                        blank=True, db_column="Pro2SrcPDB", max_length=12, null=True
                    ),
                ),
                ("pro2created", models.DateTimeField(blank=True, null=True)),
                ("pro2modified", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ser_mstr",
                "managed": False,
            },
        ),
    ]
