# Generated by Django 3.0.7 on 2022-04-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qad_ee', '0005_inmstr_lddet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InMstr',
        ),
        migrations.DeleteModel(
            name='LdDet',
        ),
    ]
