# Generated by Django 3.0.7 on 2022-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qad_ee', '0007_inmstr_lddet_sermstr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SctDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prrowid', models.CharField(max_length=36)),
                ('sct_sim', models.CharField(blank=True, max_length=80, null=True)),
                ('sct_part', models.CharField(blank=True, max_length=30, null=True)),
                ('sct_cst_tot', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_mtl_tl', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_lbr_tl', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_bdn_tl', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_ovh_tl', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_sub_tl', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_mtl_ll', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_lbr_ll', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_bdn_ll', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_ovh_ll', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_sub_ll', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_cst_date', models.DateTimeField(blank=True, null=True)),
                ('sct_user1', models.CharField(blank=True, max_length=80, null=True)),
                ('sct_user2', models.CharField(blank=True, max_length=80, null=True)),
                ('sct_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('sct_site', models.CharField(blank=True, max_length=80, null=True)),
                ('sct_rollup', models.BooleanField(blank=True, null=True)),
                ('sct_rollup_id', models.CharField(blank=True, max_length=30, null=True)),
                ('sct_nrv', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('sct_qadc01', models.CharField(blank=True, db_column='sct__qadc01', max_length=80, null=True)),
                ('sct_cost_changed', models.BooleanField(blank=True, null=True)),
                ('sct_domain', models.CharField(blank=True, max_length=8, null=True)),
                ('oid_sct_det', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('pro2srcpdb', models.CharField(blank=True, db_column='Pro2SrcPDB', max_length=12, null=True)),
                ('pro2created', models.DateTimeField(blank=True, null=True)),
                ('pro2modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sct_det',
                'managed': False,
            },
        ),
    ]
