# Generated by Django 3.1 on 2022-11-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qad_ee', '0008_sctdet'),
        ('qad_ee', '0005_sctdet'),
    ]

    operations = [
    ]
