# Generated by Django 2.1.15 on 2021-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdlineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('due_date', models.CharField(max_length=50, null=True)),
                ('item_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('to_complete', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
