# Generated by Django 4.1.5 on 2023-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpdatesProj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update", models.CharField(max_length=200, null=True)),
                ("date", models.CharField(max_length=30, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
