from django.contrib import admin
from import_export.admin import ImportExportModelAdmin

from receiving.models import *


@admin.register(LineRequestFinished)
@admin.register(LineRequestFinishedHistory)
@admin.register(LineRequestProcessing)
@admin.register(Line)
@admin.register(Justification)
@admin.register(TaskBrowse)
@admin.register(LastUpdate)
@admin.register(AreaA)
@admin.register(AreaB)
@admin.register(Kardex)
@admin.register(ReceivingPosicao1Items)
@admin.register(ReceivingPosicao2Items)
@admin.register(ReceivingPosicao3Items)
@admin.register(ReceivingPosicao4Items)
@admin.register(ReceivingPosicao5Items)
@admin.register(ReceivingPosicao6Items)
@admin.register(ReceivingPosicao7Items)
@admin.register(ReceivingPosicao8Items)
@admin.register(ReceivingPosicao1Historico)
@admin.register(ReceivingPosicao2Historico)
@admin.register(ReceivingPosicao3Historico)
@admin.register(ReceivingPosicao4Historico)
@admin.register(ReceivingPosicao5Historico)
@admin.register(ReceivingPosicao6Historico)
@admin.register(ReceivingPosicao7Historico)
@admin.register(ReceivingPosicao8Historico)
@admin.register(ReceivingSubItems)
@admin.register(ReceivingPosicao1SubItems)
@admin.register(ReceivingPosicao2SubItems)
@admin.register(ReceivingPosicao3SubItems)
@admin.register(ReceivingPosicao4SubItems)
@admin.register(ReceivingPosicao5SubItems)
@admin.register(ReceivingPosicao6SubItems)
@admin.register(ReceivingPosicao7SubItems)
@admin.register(ReceivingPosicao8SubItems)
@admin.register(HabilitarQuadrados)
@admin.register(DefinirTempos)
@admin.register(ICDR)
@admin.register(ICDRBackup)
@admin.register(ICDRmotivo)
@admin.register(UserICDR)
@admin.register(TriggerEnvioEmailsICDR)
@admin.register(ListaUsersICDR)
@admin.register(ICDRultimoValor)
@admin.register(ReceivingSubItemsTipo)
class ViewAdmin(ImportExportModelAdmin):
    pass
