# Generated by Django 2.1.15 on 2021-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducttable',
            name='tempoSupply',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
