# Generated by Django 2.1.15 on 2021-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pManagement', '0002_extraproducttable_temposupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraproducttable',
            name='tempoSupply',
            field=models.IntegerField(blank='true', default=0, null=True),
        ),
    ]
