# Generated by Django 2.1.15 on 2021-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pManagement', '0003_auto_20210824_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducttable',
            name='tempoSupplyRestante',
            field=models.IntegerField(blank='true', default=0, null=True),
        ),
    ]
