# Generated by Django 2.1.15 on 2021-09-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pManagement', '0004_extraproducttable_temposupplyrestante'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproducttable',
            name='tempoLimite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extraproducttable',
            name='ultimosDez',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
